const SIGNIN = 'SIGNIN';
const LOGOUT = 'LOGOUT';
const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
const GET_PLAYER = 'GET_PLAYER';
const GET_PLAYER_HISTORY = 'GET_PLAYER_HISTORY';

export {
  GET_PLAYER_HISTORY,
  GET_TOURNAMENTS,
  GET_PLAYER,
  SIGNIN,
  LOGOUT,
};
