const SIGNIN = 'SIGNIN';
const ERROR = 'ERROR';
const LOAD = 'LOAD';
const NEW_TOURNAMENT = 'NEW_TOURNAMENT';
const STEP_PENDING = 'STEP_PENDING';
const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
const GET_PRIZE = 'GET_PRIZE';
const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
const GET_TOURNAMENT = 'GET_TOURNAMENT';
const GET_COMPETITORS = 'GET_COMPETITORS';
const SET_PAID = 'SET_PAID';
const LOGOUT = 'LOGOUT';
const SEARCH_PLAYER = 'SEARCH_PLAYER';
const SEARCH_RESULT = 'SEARCH_RESULT';
const GET_ALL_GAMES = 'GET_ALL_GAMES';
const SEASON_GAME = 'SEASON_GAME';
const GET_SEASONS = 'GET_SEASONS';
const GET_SEASON = 'GET_SEASON';
const GET_PLAYER_PRIZES = 'GET_PLAYER_PRIZES';
const GET_TOURNAMENT_INFO_PRIZES = 'GET_TOURNAMENT_INFO_PRIZES';
const RESET_PLAYER = 'RESET_PLAYER';
const REGISTER_SALE = 'REGISTER_SALE';

export {
  REGISTER_SALE,
  RESET_PLAYER,
  GET_TOURNAMENT_INFO_PRIZES,
  GET_SEASON,
  GET_PLAYER_PRIZES,
  GET_SEASONS,
  SEASON_GAME,
  GET_ALL_GAMES,
  SIGNIN,
  ERROR,
  LOAD,
  NEW_TOURNAMENT,
  STEP_PENDING,
  GET_ALL_PLAYERS,
  GET_PRIZE,
  GET_TOURNAMENTS,
  GET_TOURNAMENT,
  GET_COMPETITORS,
  SET_PAID,
  LOGOUT,
  SEARCH_PLAYER,
  SEARCH_RESULT,
};
