const SIGNIN = 'SIGNIN';
const ERROR = 'ERROR';
const LOAD = 'LOAD';
const NEW_TOURNAMENT = 'NEW_TOURNAMENT';
const STEP_PENDING = 'STEP_PENDING';
const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
const RETRIBE_COMPETITOR = 'RETRIBE_COMPETITOR';
const ADD_PRIZE = 'ADD_PRIZE';
const GET_TOURNAMENTS = 'GET_TOURNAMENTS';

export {
  SIGNIN,
  ERROR,
  LOAD,
  NEW_TOURNAMENT,
  STEP_PENDING,
  GET_ALL_PLAYERS,
  RETRIBE_COMPETITOR,
  ADD_PRIZE,
  GET_TOURNAMENTS,
};
